export const GameList = [
    {
        id: 1,
        name: 'Uno',
        genre1: 'Cartes',
        genre2: null,
        sousGenre1: null,
        sousGenre2: null,
        minJoueurs: 2,
        maxJoueurs: 10,
        duree: '30 min',
        age: 7,
        diffculte: 1,
        langue: 'Français',
        commentaire: null,
        image: null,
        editeur: null,
        proprietaire: null
    },{
        id: 2,
        name: 'R6',
        genre1: 'Cartes',
        genre2: null,
        sousGenre1: null,
        sousGenre2: null,
        minJoueurs: 2,
        maxJoueurs: 10,
        duree: '30 min',
        age: 7,
        diffculte: 1,
        langue: 'Français',
        commentaire: null,
        image: null,
        editeur: null,
        proprietaire: null
    },{
        id: 3,
        name: 'Pokemon',
        genre1: 'Cartes',
        genre2: null,
        sousGenre1: null,
        sousGenre2: null,
        minJoueurs: 2,
        maxJoueurs: 10,
        duree: '30 min',
        age: 7,
        diffculte: 1,
        langue: 'Français',
        commentaire: null,
        image: null,
        editeur: null,
        proprietaire: null
    }
]